social_media_project/loginapp/urls.py
from django.urls import path
from loginapp import views

app_name = "loginapp"

urlpatterns = [
    path('signup/', views.signup, name= "signup"),
    path('login/', views.login_page, name= "login"),
    path('edit/', views.edit_profile, name= "edit"),
    path('logout/', views.logout_user, name= "logout"),
    path('profile/', views.user_profile, name= "profile"),
    path('user/<username>/', views.user, name= "user"),
    path('follow/<username>/', views.follow, name= "follow"),
    path('unfollow/<username>/', views.unfollow, name= "unfollow"),
]

social_media_project/postapp/urls.py
from django.urls import path
from postapp import views

app_name = "postapp"

urlpatterns = [
    path('', views.home, name= "home"),
    path('liked/<pk>/', views.liked, name= "liked"),
    path('unliked/<pk>/', views.unliked, name= "unliked"),
]

social_media_project/social_media_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from postapp import views
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('loginapp.urls')),
    path('post/', include('postapp.urls')),
    path('', views.home, name = "home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_media_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
    crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <title> {% block title_block %} Social {% endblock %} </title>

    {% block css_block %}
    {% endblock %}
</head>
<body>
    
    <div class="container" style="padding:30px">
        {% block body_block %}

        {% endblock %}
    </div>
</body>
</html>

social_media_project/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
    crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <title> {% block title_block %} Social {% endblock %} </title>

    {% block css_block %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-light navbar-light">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'postapp:home' %}">Home</a>
          </li>
          &nbsp; &nbsp; &nbsp;

          <form class="form-inline" method="GET">
            <div class="form-group">
              <input type="text" class="form-control mr-sm-2" name="search" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-success">Search</button>
          </form>
          &nbsp; &nbsp;
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'loginapp:logout' %}">Log Out</a>
          </li>

          {% if user.user_profile.profile_pic %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'loginapp:profile' %}"><img src="/media/{{ user.user_profile.profile_pic }}" 
              width="40px" height="40px" class="rounded-circle"></a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'loginapp:profile' %}"><img src="/media/blank_img.png" 
              width="40px" height="40px" class="rounded-circle"></a>
          </li>
          {% endif %}
          
        </ul>
      </nav>
    <div class="container" style="padding:30px">
        {% block body_block %}

        {% endblock %}
    </div>
</body>
</html>