social_media_project/loginapp/urls.py
from django.urls import path
from loginapp import views

app_name = "loginapp"

urlpatterns = [
    path('signup/', views.signup, name= "signup"),
    path('login/', views.login_page, name= "login"),
    path('edit/', views.edit_profile, name= "edit"),
    path('logout/', views.logout_user, name= "logout"),
    path('profile/', views.user_profile, name= "profile"),
    path('user/<username>/', views.user, name= "user"),
    path('follow/<username>/', views.follow, name= "follow"),
    path('unfollow/<username>/', views.unfollow, name= "unfollow"),
]

social_media_project/postapp/urls.py
from django.urls import path
from postapp import views

app_name = "postapp"

urlpatterns = [
    path('', views.home, name= "home"),
    path('liked/<pk>/', views.liked, name= "liked"),
    path('unliked/<pk>/', views.unliked, name= "unliked"),
]

social_media_project/social_media_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from postapp import views
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('loginapp.urls')),
    path('post/', include('postapp.urls')),
    path('', views.home, name = "home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_media_project/loginapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user_profile")
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    full_name = models.CharField(max_length=264, blank=True)
    description = models.TextField(blank=True)
    dob = models.DateField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook_id = models.URLField(blank=True)

class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name="follower")
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")
    created_date = models.DateTimeField(auto_now_add=True)

social_media_project/loginapp/forms.py
from django import forms
from loginapp.models import UserProfile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class Create_New_user(UserCreationForm):
    email = forms.EmailField(required=True, label="", widget=forms.TextInput(attrs={'placeholder':'Email'}))
    username = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password1 = forms.CharField(
        required=True,
        label="",
        widget=forms.PasswordInput(attrs={'placeholder':'Password'})
    )
    password2 = forms.CharField(
        required=True,
        label="",
        widget=forms.PasswordInput(attrs={'placeholder':'Password Confirmation'})
    )
    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')

class Edit_Profile(forms.ModelForm):
    dob = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = UserProfile()
        exclude = ('user',)

social_media_project/loginapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from loginapp.forms import Create_New_user, Edit_Profile
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from loginapp.models import UserProfile, Follow
from postapp.forms import Postform
from django.contrib.auth.models import User

# Create your views here.

def signup(request):
    form = Create_New_user()
    registered = False
    if request.method == 'POST':
        form = Create_New_user(data=request.POST)
        if form.is_valid():
            user=form.save()
            registered = True
            user_profile = UserProfile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('loginapp:login'))
    
    dict = {'form': form, 'registered': registered, 'title':'Sign up . Social'}

    return render(request, 'loginapp/signup.html', dict)

def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('postapp:home'))
    return render(request, 'loginapp/login.html', context={'title':'Login', 'form':form})

@login_required
def edit_profile(request):
    current_user = UserProfile.objects.get(user=request.user)
    form = Edit_Profile(instance=current_user)
    if request.method == 'POST':
        form = Edit_Profile(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save()
            form = Edit_Profile(instance=current_user)
            return HttpResponseRedirect(reverse('loginapp:profile'))
    return render(request, 'loginapp/profile.html', context={'form':form, 'title':'Edit Profile'})

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('loginapp:login'))

@login_required
def user_profile(request):
    form = Postform()
    if request.method == 'POST':
        form = Postform(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('home'))

    return render(request, 'loginapp/user.html', context={'title': 'User','form':form})

@login_required
def user(request, username):
    user_other = User.objects.get(username=username)
    already_followed = Follow.objects.filter(follower=request.user, following=user_other)
    if user_other == request.user:
        return HttpResponseRedirect(reverse('loginapp:profile'))
    return render (request, 'loginapp/user_other.html', context={'user_other':user_other,'already_followed':already_followed})

@login_required
def follow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following=following_user)
    if not already_followed:
        followed_user = Follow(follower=follower_user, following=following_user)
        followed_user.save()
    return HttpResponseRedirect(reverse('loginapp:user', kwargs={'username':username}))

@login_required
def unfollow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following=following_user)
    already_followed.delete()
    return HttpResponseRedirect(reverse('loginapp:user', kwargs={'username':username}))

social_media_project/templates/loginapp/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{ title }} {% endblock %}
{% block css_block %}
<style>
    .sign_up {
        width: 450px;
        border: 1px solid #ccc;
        padding: 40px;
    }
    .log_in {
        width: 450px;
        border: 1px solid #ccc;
        padding: 20px;
    }
</style>
{% endblock %}
{% block body_block %}
<center>
    <div class="log_in"> 
        <h3>Log in here:</h3>
        <form method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" style="width: 100%" class="btn btn-success">Log In</button>
        </form>
    </div>
    <br>
    <div class="sign_up">
        <p>Don't have an account? <a href="{% url 'loginapp:signup' %}">Sign Up</a></p>
    </div>
    
</center>
{% endblock %}

social_media_project/templates/loginapp/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock %}
{% block css_block %}

{% endblock %}

{% block body_block %}
<form method="POST" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Edit</button>
</form>
{% endblock %}

social_media_project/templates/loginapp/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{ title }} {% endblock %}
{% block css_block %}
<style>
    .sign_up {
        width: 450px;
        border: 1px solid #ccc;
        padding: 40px;
    }
    .log_in {
        width: 450px;
        border: 1px solid #ccc;
        padding: 20px;
    }
</style>
{% endblock %}
{% block body_block %}
<center>
    <div class="sign_up"> 
        <h3>Sign up to view post</h3>
        <form method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" style="width: 100%" class="btn btn-success">Sign Up</button>
        </form>
    </div>
    <br>
    <div class="log_in">
        <p>Already have an account? <a href="{% url 'loginapp:login' %}">Log In</a></p>
    </div>
    
</center>
{% endblock %}

social_media_project/templates/loginapp/user.html
{% extends 'navbar.html' %}
{% block title_block %} {{ user.user_profile.full_name }} (@{{user.username}}) {% endblock %}
{%block css_block%}
<style>
  .crop {
    width: 200px;
    height: 200px;
    overflow: hidden;
  }

  .crop img {
    width: 400px;
    height: 300px;
    margin: -75px 0 0 -100px;
  }
</style>
{% endblock%}

{% block body_block %}
<div class="row">
    <div class="col-sm-4">
        {% if user.user_profile.profile_pic %}
        <img src="/media/{{user.user_profile.profile_pic}}" width="250px" height="250px" class="rounded-circle">
        {% else %}
        <img src="/media/blank_img.png" width="250px" height="250px" class="rounded-circle">
        {% endif %}
    </div>
    <div class="col-sm-8">
        <h2>{{ user.username }} &nbsp; <a href="{% url 'loginapp:edit' %}" class="btn btn-success">Edit</a></h2>
        <br>
        <h4>{{user.post.count}} Posts &nbsp; &nbsp; {{user.following.count}} followers &nbsp; &nbsp; {{user.follower.count}} following</h4>
        <br>
        <h3>{{user.user_profile.full_name}}</h3>
        <h6>{{user.user_profile.description|linebreaks}}</h6>
    </div>
</div>
<hr>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    New Post
</button>
<div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Post a Photo</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
          <form method="POST" enctype="multipart/form-data">
              {{ form.as_p }}
              {% csrf_token %}
              <button type="submit">Post</button>
          </form>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
        
      </div>
    </div>
  </div>
<br>
<br>
<div class="row">
  {% for post in user.post.all %}
  <div class="crop">
    <img src="/media/{{post.image}}" title="{{post.caption}}">
  </div>
  <hr>

  {% endfor %}
</div>
{% endblock %}

social_media_project/templates/loginapp/user_other.html
{% extends 'navbar.html' %}
{%block title_block %} {{user_other.user_profile.full_name}} (@{{user_other.username}}) {%endblock%}
{%block css_block%}
<style>
  .crop {
    width: 200px;
    height: 200px;
    overflow: hidden;
  }

  .crop img {
    width: 400px;
    height: 300px;
    margin: -75px 0 0 -100px;
  }
</style>
{% endblock%}
{% block body_block %}
<div class="row">
  <div class="col-sm-4">
    {% if user_other.user_profile.profile_pic %}
    <img src="/media/{{user_other.user_profile.profile_pic}}" width="250px" height="250px" class="rounded-circle">
    {% else %}
    <img src="/media/blank_img.png" width="250px" height="250px" class="rounded-circle">
    {% endif %}
  </div>
  <div class="col-sm-8">
    <h1>{{user_other.username}} &nbsp;
      {% if not already_followed %}
      <a href="{% url 'loginapp:follow' username=user_other.username %}" class="btn btn-primary">Follow</a>
      {% else %}
      <a href="{% url 'loginapp:unfollow' username=user_other.username %}" class="btn btn-primary">Unfollow</a>
      {% endif %}
    </h1>
    <br>
    <h4>{{user_other.post.count}} posts &nbsp; &nbsp; {{user_other.following.count}} followers &nbsp; &nbsp; {{user_other.follower.count}} following</h4>
    <br>
    <h3>{{user_other.user_profile.full_name}}</h3>
    <p>{{user_other.user_profile.description|linebreaks}}</p>
  </div>
</div>
<hr>
<br>
<br>
<div class="row">
  {% for post in user_other.post.all %}
  <div class="crop">
    <img src="/media/{{post.image}}" title="{{post.caption}}">
  </div>

  {% endfor %}
</div>
{% endblock %}